pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		maven {
			name = 'Kikugie'
			url = 'https://maven.kikugie.dev/releases'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

plugins {
	id 'dev.kikugie.stonecutter' version '0.9.7'
}

stonecutter {
	create(rootProject) {
		versions("1.21.11", "26.2")
		vcsVersion = "26.2"
	}
}

rootProject.name = 'WayTooManyBinds'
